import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { NextResponse } from 'next/server';

/**
 * GET /api/attacks/report — the Step 13 attack report. Read from the
 * generated artifact when present (deterministic; regenerated by
 * pnpm demo:attacks / CI). Never runs the 60-scenario suite on load
 * (14O); an explicit ?run=1 triggers ONE fresh run server-side.
 */
export async function GET(request: Request): Promise<NextResponse> {
  const url = new URL(request.url);
  const shouldRun = url.searchParams.get('run') === '1';
  try {
    if (shouldRun) {
      const { runAttackSuite } = await import('@agent-trust/attacks');
      const report = await runAttackSuite();
      return NextResponse.json(report);
    }
    const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../../../../');
    const file = join(repoRoot, 'artifacts/attacks/attack-report.json');
    if (existsSync(file)) {
      return NextResponse.json(JSON.parse(readFileSync(file, 'utf8')));
    }
    // First-run convenience: generate once, then serve the file.
    const { runAttackSuite } = await import('@agent-trust/attacks');
    const report = await runAttackSuite();
    return NextResponse.json(report);
  } catch (e) {
    return NextResponse.json(
      { error: 'ATTACK_REPORT_UNAVAILABLE', detail: e instanceof Error ? e.message : String(e) },
      { status: 503 },
    );
  }
}
