import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { NextResponse } from 'next/server';

import { ATTACKS_DIR } from '@/server/world';

/**
 * GET /api/attacks/report — the Step 13 attack report. Read from the
 * generated artifact when present (deterministic; regenerated by
 * pnpm demo:attacks / CI, and baked into the demo image at build time).
 * Never runs the 60-scenario suite on load (14O); an explicit ?run=1
 * triggers ONE fresh run server-side.
 */
export async function GET(request: Request): Promise<NextResponse> {
  const url = new URL(request.url);
  const shouldRun = url.searchParams.get('run') === '1';
  try {
    if (!shouldRun) {
      // Single source of truth for the repo root (env → walk-up → cwd),
      // safe inside the webpack server bundle.
      const file = join(ATTACKS_DIR, 'attack-report.json');
      if (existsSync(file)) {
        return NextResponse.json(JSON.parse(readFileSync(file, 'utf8')));
      }
      // First-run convenience: generate once, then serve the file.
    }
    const { runAttackSuite } = await import('@agent-trust/attacks');
    const report = await runAttackSuite();
    return NextResponse.json(report);
  } catch (e) {
    return NextResponse.json(
      { error: 'ATTACK_REPORT_UNAVAILABLE', detail: e instanceof Error ? e.message : String(e) },
      { status: 503 },
    );
  }
}
